language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
env:
  global:
    - NODE_ENV=test
before_script:
  - bundle exec rake db:schema:load RAILS_ENV=test
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
script:
  - bundle exec rails webpacker:compile
  - bundle exec rspec
deploy:
  provider: heroku
  # api_key:
  app: https://grumblr-lhje.herokuapp.com/
  run: rails db:migrate
