language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate,seed} RAILS_ENV=test
- RAILS_ENV=test bundle exec rails webpacker:compile
- bundle exec rspec
deploy:
  provider: heroku
  # api_key:
  app: https://grumblr-lhje.herokuapp.com/
  run: rails db:migrate
